### ISSUE TITLE
Basebackup binlog_info RegExp compile errors for multiple gtid groups.

### ISSUE THREAD

**Issue by enhellowhy** [aiven/myhoard#42]
![image](https://user-images.githubusercontent.com/18282440/103117300-b7f80e00-46a4-11eb-90f5-f1ea778d21eb.png)
![image](https://user-images.githubusercontent.com/18282440/103117726-c1827580-46a6-11eb-9124-7206e97c43eb.png)

i want to know if it will impact the restore data from the basebackup?

**Comment by rikonen** [comment]
Thank you for the report. This looks to be a valid issue and could affect restoration. We'll look into fixing this as soon as possible.

**Comment by rikonen** [comment]
This issue doesn't seem to be reproducible with a recent version of XtraBackup, which strips linefeeds away in `log_status_local_parse` function. Similar logic does not exist for XtraBackup 2.4 but that and MySQL versions prior to 8.0 are currently not supported.

Could you please provide the exact XtraBackup version that was used to reproduce this issue?

**Comment by enhellowhy** [comment]
Percona MySQL
![image](https://user-images.githubusercontent.com/18282440/103355499-5f33d580-4ae9-11eb-88b9-b17fd6c89493.png)

XtraBackup version
![image](https://user-images.githubusercontent.com/18282440/103355606-973b1880-4ae9-11eb-89d7-2f4ca4f7512c.png)

Thanks for your reply.

**Comment by rikonen** [comment]
Thank you. That version is currently unsupported. This branch https://github.com/aiven/myhoard/compare/rauli-mysql57?expand=1 has some of the required changes but at the moment we are not going to add official 5.7 support ourselves so closing this issue. It will be addressed if MySQL 5.7 / XtraBackup 2.4 will be supported later.
