### ISSUE TITLE
Intermittent build workflow failures

### ISSUE THREAD

**Issue by st3fan** [aiven/myhoard#77]
Quick note to mention that I got a number of intermittent test errors on the two PRs I submitted today. I tried to discover the root cause but my knowledge of MySQL and these tests is limited. I did re-run the failed jobs and eventually they all succeeded.

**Comment by alanfranz-at-work** [comment]
This should be fixed with #82 . If you still encounter intermittent failures, it's at least easier to check what's happening on your own workstation and see if it's just flaky infrastructure or a real problem.
